library(grid)
source("pwm.R")
source("seqLogo.R")
source("seqLogo2_figS2.R")

pwm=as.matrix(read.table("cons_dm6_K6_s1_1.mat", header=F))
pwm=t(pwm/rowSums(pwm))
pdf("figS2_dm6_class1_logo.pdf",2.7,2.0)
seqLogo2(pwm,xfontsize=6, yfontsize=6, title="Class 1, 88.9%")
dev.off()

pwm=as.matrix(read.table("cons_dm6_K6_s1_2.mat", header=F))
pwm=t(pwm/rowSums(pwm))
pdf("figS2_dm6_class2_logo.pdf",2.7,2.0)
seqLogo2(pwm,xfontsize=6, yfontsize=6, title="Class 2, 2.8%")
dev.off()

pwm=as.matrix(read.table("cons_dm6_K6_s1_3.mat", header=F))
pwm=t(pwm/rowSums(pwm))
pdf("figS2_dm6_class3_logo.pdf",2.7,2.0)
seqLogo2(pwm,xfontsize=6, yfontsize=6, title="Class 3, 2.7%")
dev.off()

pwm=as.matrix(read.table("cons_dm6_K6_s1_4.mat", header=F))
pwm=t(pwm/rowSums(pwm))
pdf("figS2_dm6_class4_logo.pdf",2.7,2.0)
seqLogo2(pwm,xfontsize=6, yfontsize=6, title="Class 4, 2.5")
dev.off()

pwm=as.matrix(read.table("cons_dm6_K6_s1_5.mat", header=F))
pwm=t(pwm/rowSums(pwm))
pdf("figS2_dm6_class5_logo.pdf",2.7,2.0)
seqLogo2(pwm,xfontsize=6, yfontsize=6, title="Class 5, 1.6%")
dev.off()

pwm=as.matrix(read.table("cons_dm6_K6_s1_6.mat", header=F))
pwm=t(pwm/rowSums(pwm))
pdf("figS2_dm6_class6_logo.pdf",2.7,2.0)
seqLogo2(pwm,xfontsize=6, yfontsize=6, title="Class 6, 1.6%")
dev.off()
