library(grid)
source("pwm.R")
source("seqLogo.R")
source("seqLogo2_fig2.R")

pwm=as.matrix(read.table("cons_dm6_K3_s1_1.mat", header=F))
pwm=t(pwm/rowSums(pwm))
pdf("fig2_dm6_class1_logo.pdf",2.7,2.0)
seqLogo2(pwm,xfontsize=6, yfontsize=6, title="Class 1 (Inr+DPE), 37.2%")
dev.off()

pwm=as.matrix(read.table("cons_dm6_K3_s1_2.mat", header=F))
pwm=t(pwm/rowSums(pwm))
pdf("fig2_dm6_class2_logo.pdf",2.7,2.0)
seqLogo2(pwm,xfontsize=6, yfontsize=6, title="Class 2 (Inr), 33.8%")
dev.off()

pwm=as.matrix(read.table("cons_dm6_K3_s1_3.mat", header=F))
pwm=t(pwm/rowSums(pwm))
pdf("fig2_dm6_class3_logo.pdf",2.7,2.0)
seqLogo2(pwm,xfontsize=6, yfontsize=6, title="Class 3 (weak non-canonical Inr), 29.0%")
dev.off()

pwm=as.matrix(read.table("cons_dm6_K3_s1_1.mat", header=F))
pwm=t(pwm/rowSums(pwm))
pdf("fig2_hg19_class1_logo.pdf",2.7,2.0)
seqLogo2(pwm,xfontsize=6, yfontsize=6, title="Class 1 (Inr), 47.1%")
dev.off()

pwm=as.matrix(read.table("cons_dm6_K3_s1_2.mat", header=F))
pwm=t(pwm/rowSums(pwm))
pdf("fig2_hg19_class2_logo.pdf",2.7,2.0)
seqLogo2(pwm,xfontsize=6, yfontsize=6, title="Class 2 (weak non-canonical Inr), 28.7%")
dev.off()

pwm=as.matrix(read.table("cons_dm6_K3_s1_3.mat", header=F))
pwm=t(pwm/rowSums(pwm))
pdf("fig2_hg19_class3_logo.pdf",2.7,2.0)
seqLogo2(pwm,xfontsize=6, yfontsize=6, title="Class 3, 24.2%")
dev.off()
